#!/bin/bash

# Run the Python script to get substitutions
substitutions=$(python generate_substitutions.py)

# Loop over each substitution
for sub in $substitutions; do
    
    # Create a FASTA file within the directory
    fasta_file="${sub}/SlCLV1_${sub}.fasta"
    echo ">SlCLV1_${sub}" > "$fasta_file"
    echo "MVAPGTSALLDWNNNTKNYPFSHCSFSGITCNNNSHVISINITNVPLFGTIPPEIGLLQNLENLTIFGDNLTGTLPLEMSQLSSIKHVNLSYNNFSGPFPREILLGLIKLESFDIYNNNFTGELPIEVVKLKNLETLHLGGNYFHGEIPEVYSHIVSLKWLGLEGNSLTGKIPKSLALLPNLEELRLGYYNSYEGGIPSEFGNISTLKLLDLGNCNLDGEVPPSLGNLKKLHSLFLQVNRLTGHIPSELSGLESLMSFDLSFNQLTGEIPESFVKLQKLTLINLFRNNLHGPIPSFIGDLPNLEVLQIWGNNFTLELPENLGRNGRLLFLDISINHFTGRIPPDLCKGGKLKTLILMENYFFGPIPEQLGECKSLTRIRVRKNYLNGTIPAGFFKLPALDMLELDNNYFTGELPTEINANNLTKLVLSNNWITGNIPPSLGNLKNLVTLSLDVNRLSGEIPQEIASLNKLVTINLSGNNLTGEIPSSIALCSELTLVDLSRNQLVGEVPKEITKLNSLNALNLSRNQLSGAIPGEV:" >> "$fasta_file"
    echo "$sub" >> "$fasta_file"
done
